In [2]:
import numpy as np

## The Basics

In [17]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
#get dimension
b.ndim

2

In [9]:
b.shape

(2, 3)

In [14]:
a.dtype

dtype('int16')

In [22]:
a.itemsize
b.itemsize

8

In [21]:
#get total size
a.size * a.itemsize
a.nbytes

12

In [23]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
#Get a specific element [r, c]
a[1,-1]

14

In [26]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
#get a column
a[:,3]

array([ 4, 11])

In [31]:
#[startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [35]:
a[1,5]=20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [37]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
b[0,1,1]

4

## Initializing Different Types of Arrays

In [40]:
#All 0s matrix

np.zeros((2,3)) #2 dimensional

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
#Any other number
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [45]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [49]:
#random integer
np.random.randint(4, 7,size=(3,3)) 

array([[5, 5, 5],
       [5, 6, 4],
       [6, 6, 6]])

In [46]:
np.random.rand(4,2)

array([[0.7310902 , 0.44000433],
       [0.50249392, 0.56454482],
       [0.05507755, 0.2691498 ],
       [0.61521157, 0.48687535]])

In [50]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
#repeat
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [57]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### careful when copying arrays

In [59]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a,b)

[1 2 3] [100   2   3]


## Math

In [62]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [63]:
a += 2 # [3 4 5 6]
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

### Linear Algebra

In [66]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [68]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [69]:
stats = np.array([[1,2,3],[4,5,6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
np.min(stats)

1

In [71]:
np.max(stats,axis=1)

array([3, 6])

In [73]:
np.sum(stats, axis=1)

array([ 6, 15])

### Reorganizing arrays

In [77]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [79]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
#Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Load data from files

In [82]:
filedata = np.genfromtxt('data.txt',delimiter=',')

AttributeError: module 'numpy' has no attribute 'getfromtxt'